### ISSUE TITLE
Error when uploading

### ISSUE THREAD

**Issue by aphamani** [davidbmaier/discord-recap#20] opened 2024-03-15 12:19 UTC
I get this error when I upload the package.zip, I got my data 3hrs ago. Thank you!

chunk-F3NYKV2Z.js:7 TypeError: Cannot read properties of null (reading 'content')
    at E9 (chunk-H7Q3MJJL.js:34:825)
    at Zi (chunk-F3NYKV2Z.js:5:52842)
    at na (chunk-F3NYKV2Z.js:9:8687)
    at qs (chunk-F3NYKV2Z.js:9:933)
    at Qf (chunk-F3NYKV2Z.js:9:864)
    at ut (chunk-F3NYKV2Z.js:9:724)
    at yi (chunk-F3NYKV2Z.js:7:10856)
    at chunk-F3NYKV2Z.js:5:38670
    at L.unstable_runWithPriority (chunk-F3NYKV2Z.js:1:4026)
    at rn (chunk-F3NYKV2Z.js:5:38448)
ui @ chunk-F3NYKV2Z.js:7

chunk-F3NYKV2Z.js:7 TypeError: Cannot read properties of null (reading 'date')
    at o (chunk-H7Q3MJJL.js:31:38715)
    at O9 (chunk-H7Q3MJJL.js:32:75)
    at Zi (chunk-F3NYKV2Z.js:5:52842)
    at na (chunk-F3NYKV2Z.js:9:8687)
    at qs (chunk-F3NYKV2Z.js:9:933)
    at Qf (chunk-F3NYKV2Z.js:9:864)
    at ut (chunk-F3NYKV2Z.js:9:724)
    at yi (chunk-F3NYKV2Z.js:7:10856)
    at chunk-F3NYKV2Z.js:5:38670
    at L.unstable_runWithPriority (chunk-F3NYKV2Z.js:1:4026)
ui @ chunk-F3NYKV2Z.js:7

root-N7Z4GSUZ.js:1 TypeError: Cannot read properties of null (reading 'date')
    at o (chunk-H7Q3MJJL.js:31:38715)
    at O9 (chunk-H7Q3MJJL.js:32:75)
    at Zi (chunk-F3NYKV2Z.js:5:52842)
    at na (chunk-F3NYKV2Z.js:9:8687)
    at qs (chunk-F3NYKV2Z.js:9:933)
    at Qf (chunk-F3NYKV2Z.js:9:864)
    at ut (chunk-F3NYKV2Z.js:9:724)
    at yi (chunk-F3NYKV2Z.js:7:10856)
    at chunk-F3NYKV2Z.js:5:38670
    at L.unstable_runWithPriority (chunk-F3NYKV2Z.js:1:4026)

<img width="672" alt="image" src="https://github.com/davidbmaier/discord-recap/assets/71981370/078ec3bf-5bdc-42d0-9c5c-ffc4a56dc31c">

**Comment by davidbmaier** [comment] 2024-03-19 15:03
Unfortunately it's always difficult to debug these kinds of issues since I only have access to my own data packages. I can't reproduce the issue with my last one from December, but I've requested a new one to see if the format might have changed since then.
Otherwise it may be something specific in your package. Did this happen during the processing of the package or later when you were already looking at the stats?

**Comment by aphamani** [comment] 2024-03-20 07:07
My friend has the same issue, it seems that it does not work with new data! It happens when immediately when I clicked the button

**Comment by davidbmaier** [comment] 2024-03-22 10:37
Just got my latest data package and I can reproduce the problem - will have a look this weekend.

**Comment by davidbmaier** [comment] 2024-03-22 16:38
Discord indeed changed their message file format from XML to JSON, and the site didn't know how to handle that - should be fixed in 4e22e5ef20bff4491dad53f5ffdb8d013d2ee130 (which is live already).
Let me know if that works for you @aphamani (you'll have to let the site scan your package again) or if you still see issues on your end.

**Comment by aphamani** [comment] 2024-03-24 23:39
It's working perfectly, thank you !! @davidbmaier

**Closed as completed** 2024-03-24 23:40 UTC
Labels: bug
