### ISSUE TITLE
[Suggestion] HTML export feature

### ISSUE THREAD

**Issue by Pandaptable** [davidbmaier/discord-recap#9] opened 2022-06-16 09:11 UTC
Would absolutely love a way to have an html file that you could open locally that has all your stats in the same design as the webpage. May be a better file format, just the first that I can think of. 
I know you can run it locally and open your package yourself, however it would be missing the emojis and possibly something else I'm forgetting that needs internet access.

**Comment by davidbmaier** [comment] 2022-06-16 10:37
Hmm, interesting idea.
Maybe as a boiled-down version of just the main stats, otherwise it would get fairly heavy and unorganized I think.
Are you thinking of it as a sort of shareable file that you could send to others, or just a way to look at the stats without having internet access?

**Comment by Pandaptable** [comment] 2022-06-16 21:44
> Hmm, interesting idea. Maybe as a boiled-down version of just the main stats, otherwise it would get fairly heavy and unorganized I think. Are you thinking of it as a sort of shareable file that you could send to others, or just a way to look at the stats without having internet access?

Main idea was as a sharable file. However not having internet access and being able to view stats would be a perk of it.

**Comment by davidbmaier** [comment] 2022-06-16 22:14
Gotcha, I'll have to think about it. My current idea would be a Share button that generates an image with the most important stats in the page's design and lets you download it.
Not sure how fast I'd get to that, I kind of considered the site feature-complete and haven't looked at it in a while 😅 But I'll try and take a look this weekend if I can quickly figure something out.

**Comment by Pandaptable** [comment] 2022-06-17 01:52
sounds great! would love a mention of some sort if you get to it!

**Comment by davidbmaier** [comment] 2022-06-17 11:56
Alright, I got to it a little earlier than I thought.
I added a Share button to the footer of the page on desktop, which will generate and download an image that contains the most important stats that you can see on the main page.

A couple restrictions:
- Because of the way it generates the image, mobile is out of scope for now. I don't think there are many people using the site on mobile anyway (scanning a package takes quite a bit longer there), so I don't think that'll be a huge problem.
- I thought about including a lot more data from other pages, but it gets complicated pretty fast - I'm effectively taking a screenshot of a modified version of the visible page, and fitting more data in there would require a bit more logic. Even if I did that, it would likely only include a handful of stats, not the full data set.
- All the server/channel/DM-specific stuff is only available on the website. Fitting that into an image or making it configurable is just too much effort at the moment.
- Some of the external images (specifically the emotes) might have some pixel errors. Not sure what's that's caused by, might just be a limitation of how I'm doing it. I could look into it later, but I don't have much hope that I'd find an easy fix.

@Pandaptable Let me know if it works for you and any feedback you have. It's not a full offline version of the entire site, but I think it works as a shareable image with quite a bit of content.

Here's an example what mine looks like:
![grafik](https://user-images.githubusercontent.com/17618532/174293366-ab00ad23-4d68-45ad-840e-135d4e9f59aa.png)

**Closed as completed** 2022-06-23 21:52 UTC
Labels: enhancement
